name: Deploy Docker

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  push:
    branches:
        - main

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        run: |
          # new login with new container registry url and PAT
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
                    
      - name: Build Docker Image
        run: |
          docker build -t docker_image .
          
      - name: Push to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # If we there is a version tag publish an image with version tag
          [[ "${{ github.ref }}" == "refs/tags/"* ]] \
            && VERSION=$(echo $VERSION | sed -e 's/^v//') \
            && docker tag docker_image $IMAGE_ID:$VERSION \
            && docker push $IMAGE_ID:$VERSION

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,') 

          # Use for main branch use `latest` tag convention
          [ "$VERSION" == "main" ] && docker tag docker_image $IMAGE_ID:latest
          [ "$VERSION" == "main" ] && docker push $IMAGE_ID:latest

          # For other branches use branch as tag
          [ "$VERSION" != "main ] && docker tag docker_image $IMAGE_ID:$VERSION
          [ "$VERSION" != "main ] && docker push $IMAGE_ID:$VERSION
